"""Code generation for the AgentBus web UI.

The UI lets users design workflows without hand-writing Python. Nodes and topic
schemas are still real Python (the bus loads them by import path via
``build_bus_from_config``) — this module *generates* that code from structured
specs and writes it into a project-local package (default ``agentbus_workflow``).

Layout written under ``<root>/<package>/``::

    agentbus_workflow/
        __init__.py
        schemas/__init__.py
        schemas/<snake>.py     # class <Name>(BaseModel)
        nodes/__init__.py
        nodes/<snake>.py       # class <Name>(Node)

Each entity gets its own module so regenerating one never has to parse or
rewrite another. Import paths handed back to the config are
``<package>.schemas.<snake>:<Name>`` and ``<package>.nodes.<snake>:<Name>``.
"""

import importlib
import keyword
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from agentbus.harness.session import _atomic_write_text

# Pydantic-friendly type names the UI may send → Python annotation.
_TYPE_MAP = {
    "str": "str",
    "string": "str",
    "int": "int",
    "integer": "int",
    "float": "float",
    "number": "float",
    "bool": "bool",
    "boolean": "bool",
    "list": "list",
    "dict": "dict",
    "any": "Any",
}


class CodegenError(ValueError):
    """Raised when a spec is invalid or generated code fails to import."""


@dataclass
class FieldSpec:
    name: str
    type: str = "str"
    required: bool = True
    default: object = None
    description: str = ""


@dataclass
class SchemaSpec:
    class_name: str
    fields: list[FieldSpec] = field(default_factory=list)
    description: str = ""

    def __post_init__(self) -> None:
        self.fields = [f if isinstance(f, FieldSpec) else FieldSpec(**f) for f in self.fields]


@dataclass
class NodeSpec:
    class_name: str
    node_name: str
    subscriptions: list[str] = field(default_factory=list)
    publications: list[str] = field(default_factory=list)
    concurrency: int = 1
    concurrency_mode: str = "parallel"
    # Hook bodies as raw Python source (already de-indented to column 0). Empty
    # strings mean "emit a `pass` body". on_message is always emitted.
    hooks: dict[str, str] = field(default_factory=dict)
    description: str = ""


# ── Validation helpers ────────────────────────────────────────────────────────


def _valid_identifier(name: str) -> bool:
    return name.isidentifier() and not keyword.iskeyword(name)


def slugify(class_name: str) -> str:
    """``MyEventNode`` → ``my_event_node`` for use as a module file name."""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", class_name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    slug = re.sub(r"[^0-9a-zA-Z]+", "_", s2).strip("_").lower()
    if not slug or slug[0].isdigit():
        slug = f"m_{slug}"
    return slug


# ── Source generation (pure functions) ────────────────────────────────────────


def _indent(body: str, spaces: int) -> str:
    pad = " " * spaces
    lines = body.rstrip("\n").splitlines() or ["pass"]
    return "\n".join(pad + line if line.strip() else line for line in lines)


def generate_schema_source(spec: SchemaSpec) -> str:
    if not _valid_identifier(spec.class_name):
        raise CodegenError(f"invalid schema class name: {spec.class_name!r}")

    uses_any = any(_TYPE_MAP.get(f.type, "Any") == "Any" for f in spec.fields)

    lines: list[str] = ['"""Generated by the AgentBus UI. Edit freely."""', ""]
    if uses_any:
        lines += ["from typing import Any", ""]
    lines += ["from pydantic import BaseModel", "", ""]
    lines.append(f"class {spec.class_name}(BaseModel):")
    if spec.description:
        lines.append(f'    """{spec.description}"""')
        lines.append("")

    if not spec.fields:
        lines.append("    pass")
    for f in spec.fields:
        if not _valid_identifier(f.name):
            raise CodegenError(f"invalid field name: {f.name!r}")
        ann = _TYPE_MAP.get(f.type, "Any")
        if f.required and f.default is None:
            lines.append(f"    {f.name}: {ann}")
        else:
            lines.append(f"    {f.name}: {ann} = {f.default!r}")

    return "\n".join(lines) + "\n"


def generate_node_source(spec: NodeSpec) -> str:
    if not _valid_identifier(spec.class_name):
        raise CodegenError(f"invalid node class name: {spec.class_name!r}")
    if not spec.node_name:
        raise CodegenError("node_name is required")
    if spec.concurrency_mode not in ("parallel", "serial"):
        raise CodegenError(f"invalid concurrency_mode: {spec.concurrency_mode!r}")

    lines: list[str] = [
        '"""Generated by the AgentBus UI. Edit freely."""',
        "",
        "from agentbus.message import Message",
        "from agentbus.node import BusHandle, Node",
        "",
        "",
        f"class {spec.class_name}(Node):",
    ]
    if spec.description:
        lines.append(f'    """{spec.description}"""')
        lines.append("")
    lines.append(f"    name = {spec.node_name!r}")
    lines.append(f"    subscriptions = {list(spec.subscriptions)!r}")
    lines.append(f"    publications = {list(spec.publications)!r}")
    if spec.concurrency != 1:
        lines.append(f"    concurrency = {spec.concurrency}")
    if spec.concurrency_mode != "parallel":
        lines.append(f"    concurrency_mode = {spec.concurrency_mode!r}")

    # on_init / on_shutdown only if a body was supplied; on_message always.
    if spec.hooks.get("on_init", "").strip():
        lines += [
            "",
            "    async def on_init(self, bus: BusHandle) -> None:",
            _indent(spec.hooks["on_init"], 8),
        ]
    lines += [
        "",
        "    async def on_message(self, msg: Message) -> None:",
        _indent(spec.hooks.get("on_message", ""), 8),
    ]
    if spec.hooks.get("on_shutdown", "").strip():
        lines += [
            "",
            "    async def on_shutdown(self) -> None:",
            _indent(spec.hooks["on_shutdown"], 8),
        ]

    return "\n".join(lines) + "\n"


# ── Workspace (writes files + validates imports) ──────────────────────────────


_INIT_DOC = '"""Generated AgentBus workflow package."""\n'


class CodegenWorkspace:
    """Owns the on-disk generated package and turns specs into importable code."""

    def __init__(self, root: Path | str, package: str = "agentbus_workflow") -> None:
        self.root = Path(root)
        self.package = package
        self.pkg_dir = self.root / package

    def _ensure_pkg(self) -> None:
        for sub in (self.pkg_dir, self.pkg_dir / "schemas", self.pkg_dir / "nodes"):
            init = sub / "__init__.py"
            if not init.exists():
                _atomic_write_text(init, _INIT_DOC)

    def write_schema(self, spec: SchemaSpec) -> str:
        """Generate, write, validate. Returns the ``module:Class`` import path."""
        self._ensure_pkg()
        source = generate_schema_source(spec)
        module = slugify(spec.class_name)
        _atomic_write_text(self.pkg_dir / "schemas" / f"{module}.py", source)
        import_path = f"{self.package}.schemas.{module}:{spec.class_name}"
        self.validate_import(import_path)
        return import_path

    def write_node(self, spec: NodeSpec) -> str:
        self._ensure_pkg()
        source = generate_node_source(spec)
        module = slugify(spec.class_name)
        _atomic_write_text(self.pkg_dir / "nodes" / f"{module}.py", source)
        import_path = f"{self.package}.nodes.{module}:{spec.class_name}"
        self.validate_import(import_path)
        return import_path

    def validate_import(self, import_path: str) -> object:
        """Import the generated symbol so syntax/import errors surface eagerly.

        ``root`` must be importable (on ``sys.path``); the server ensures this by
        inserting ``root`` at process start. Invalidates import caches so a
        freshly written module is picked up without a restart.
        """
        module_name, _, attr = import_path.partition(":")
        importlib.invalidate_caches()
        try:
            if module_name in sys.modules:
                module = importlib.reload(sys.modules[module_name])
            else:
                module = importlib.import_module(module_name)
            return getattr(module, attr)
        except Exception as exc:
            raise CodegenError(f"generated code failed to import ({import_path}): {exc}") from exc


__all__ = [
    "CodegenError",
    "CodegenWorkspace",
    "FieldSpec",
    "NodeSpec",
    "SchemaSpec",
    "generate_node_source",
    "generate_schema_source",
    "slugify",
]
